# Generated by Django 3.2.3 on 2022-12-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.cat'),
            preserve_default=False,
        ),
    ]
