# Generated by Django 3.2.3 on 2022-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reiting',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
